name: ap_micromacro
macro_channels: 32
n_fno_blocks: 4
n_modes: 12
micro_latent_dim: 64
micro_hidden: [128, 128]
n_freq_x: 16
n_freq_omega: 8
activation: gelu
time_dependent: false
n_bc_faces: 4
moment_order: 1
lambda_moment: 1.0
lambda_diffusion: 0.1
